[[plugins]]
repo    = 'Shougo/dein.vim'

[[plugins]]
repo    = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'

[[plugins]]
repo    = 'tomtom/tcomment_vim'

[[plugins]]
repo    = 'terryma/vim-multiple-cursors'
hook_add = '''
let g:multi_cursor_select_all_key      = '<f2>'
'''

[[plugins]]
repo    = 'deris/vim-rengbang'

[[plugins]]
repo    = 'h1mesuke/vim-alignta'

[[plugins]]
repo    = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline#extensions#tabline#enabled = 0
let g:airline_theme = 'papercolor'
'''

# [[plugins]]
# repo = 'Townk/vim-autoclose'

# [[plugins]]
# repo = 'Yggdroot/indentLine'
# hook_add = '''
# let g:indentLine_char = '¦'
# '''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


[[plugins]]
repo = 'junegunn/vim-easy-align'


[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config={'*': {'split': ''}}
'''

# ウインドウのリサイズを簡単にする
# c-eでリサイズモード開始
[[plugins]]
repo = 'simeji/winresizer'

# チートシート
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
let g:cheatsheet#cheat_file = '~/.vimCheat.md'
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_statusline_format = ['E%d', 'W%d', 'OK']

nmap <silent> <C-w>j <Plug>(ale_next_wrap)
nmap <silent> <C-w>k <Plug>(ale_previous_wrap)

let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier-eslint']

" ファイル保存時に実行
let g:ale_fix_on_save = 1

" ローカルの設定ファイルを考慮する
let g:ale_javascript_prettier_use_local_config = 1
'''
